// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAckzyvKOlmZdfDi3ATVq5JSDieYWACgY',
    appId: '1:218160437712:web:df46f86a85d763535cc1d5',
    messagingSenderId: '218160437712',
    projectId: 'coffeskuy-auth-1941d',
    authDomain: 'coffeskuy-auth-1941d.firebaseapp.com',
    storageBucket: 'coffeskuy-auth-1941d.appspot.com',
    measurementId: 'G-SN8498P8B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLJn8L8smfGJo4C-um2Rf4w1y32MEg3hk',
    appId: '1:218160437712:android:ef2c63af93536a455cc1d5',
    messagingSenderId: '218160437712',
    projectId: 'coffeskuy-auth-1941d',
    storageBucket: 'coffeskuy-auth-1941d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBEs9URa6J8wGLdTJRnKwIx5urTLJwm4',
    appId: '1:218160437712:ios:1ce2869788b76b8f5cc1d5',
    messagingSenderId: '218160437712',
    projectId: 'coffeskuy-auth-1941d',
    storageBucket: 'coffeskuy-auth-1941d.appspot.com',
    iosBundleId: 'com.example.coffeskuyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBEs9URa6J8wGLdTJRnKwIx5urTLJwm4',
    appId: '1:218160437712:ios:11c704bc2d4488b35cc1d5',
    messagingSenderId: '218160437712',
    projectId: 'coffeskuy-auth-1941d',
    storageBucket: 'coffeskuy-auth-1941d.appspot.com',
    iosBundleId: 'com.example.coffeskuyapp.RunnerTests',
  );
}
